version: '3.3'

volumes:
  db_data_volume: { }

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: coras
    volumes:
      - type: volume
        source: db_data_volume
        target: /var/lib/mysql
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
