volumes:
  db_data_volume: {}

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "127.0.0.1:3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: coras
    volumes:
      - type: volume
        source: db_data_volume
        target: /var/lib/mysql
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql

  spacy_micro-service:
    image: ls6uniwue/coras_spacy
    restart: always
    ports:
      - "127.0.0.1:5011:8000"
