env:
  browser: true
  es2021: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent: [ 'off', 2 ] # TODO: ignore indent for now...
  linebreak-style: [ 'error' , 'unix' ]
  quotes: [ 'warn', 'single' ]
  semi: [ 'warn', 'always' ]
  '@typescript-eslint/no-extra-non-null-assertion': [ 'warn' ]
  'react/react-in-jsx-scope': [ 'off' ] # not needed anymore in react 17
